export const mockUsers = [
  {
    id: '1',
    full_name: 'John Doe',
    role: 'citizen',
    email: 'john@example.com',
    notification_enabled: true,
    points: 450,
    language_preference: 'en',
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    full_name: 'Jane Smith',
    role: 'admin',
    email: 'jane@example.com',
    notification_enabled: true,
    points: 890,
    language_preference: 'en',
    created_at: '2024-01-10T08:00:00Z',
  },
  {
    id: '3',
    full_name: 'Mike Johnson',
    role: 'ward_officer',
    email: 'mike@example.com',
    notification_enabled: true,
    ward_zone: 'Ward 5',
    points: 320,
    language_preference: 'en',
    created_at: '2024-02-01T09:00:00Z',
  },
  {
    id: '4',
    full_name: 'Sarah Williams',
    role: 'field_officer',
    email: 'sarah@example.com',
    notification_enabled: true,
    points: 650,
    language_preference: 'en',
    created_at: '2024-01-20T11:00:00Z',
  },
  {
    id: '5',
    full_name: 'David Brown',
    role: 'field_officer',
    email: 'david@example.com',
    notification_enabled: true,
    points: 280,
    language_preference: 'en',
    created_at: '2024-02-15T10:30:00Z',
  },
];

export const mockIssues = [
  {
    id: '1',
    ticket_id: 'IMP-2024-0001',
    title: 'Large pothole on Main Street',
    description: 'There is a dangerous pothole near the intersection of Main St and 5th Ave. It has been causing problems for vehicles and needs urgent attention.',
    category: 'road',
    status: 'in_progress',
    severity: 'high',
    priority_score: 32.5,
    upvotes: 15,
    ai_category: 'road',
    ai_confidence: 0.92,
    photo_url: 'https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7128,
    longitude: -74.0060,
    address: '1250 Main Street, New York, NY',
    reported_by: '1',
    assigned_to: '4',
    is_anonymous: false,
    created_at: '2024-03-01T09:30:00Z',
    updated_at: '2024-03-05T14:20:00Z',
    reporter: mockUsers[0],
    assignee: mockUsers[3],
  },
  {
    id: '2',
    ticket_id: 'IMP-2024-0002',
    title: 'Streetlight not working',
    description: 'The streetlight at Park Avenue has been out for over a week, making the area unsafe at night.',
    category: 'lighting',
    status: 'resolved',
    severity: 'medium',
    priority_score: 22.3,
    upvotes: 8,
    ai_category: 'lighting',
    ai_confidence: 0.95,
    photo_url: 'https://images.pexels.com/photos/1108701/pexels-photo-1108701.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7589,
    longitude: -73.9851,
    address: '890 Park Avenue, Manhattan, NY',
    reported_by: '4',
    is_anonymous: false,
    created_at: '2024-02-20T18:45:00Z',
    updated_at: '2024-02-28T10:15:00Z',
    reporter: mockUsers[3],
  },
  {
    id: '3',
    ticket_id: 'IMP-2024-0003',
    title: 'Overflowing garbage bins',
    description: 'Multiple garbage bins on Elm Street have been overflowing for days. This is attracting pests and creating an unsanitary environment.',
    category: 'waste',
    status: 'in_progress',
    severity: 'high',
    priority_score: 28.7,
    upvotes: 22,
    ai_category: 'waste',
    ai_confidence: 0.89,
    photo_url: 'https://images.pexels.com/photos/2768961/pexels-photo-2768961.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7306,
    longitude: -73.9352,
    address: '432 Elm Street, Brooklyn, NY',
    reported_by: '1',
    assigned_to: '3',
    is_anonymous: false,
    created_at: '2024-03-10T08:15:00Z',
    updated_at: '2024-03-10T08:15:00Z',
    reporter: mockUsers[0],
    assignee: mockUsers[2],
  },
  {
    id: '4',
    ticket_id: 'IMP-2024-0004',
    title: 'Water leak in community park',
    description: 'Noticed a water leak near the fountain in Central Park. Water is continuously flowing and being wasted.',
    category: 'water',
    status: 'in_progress',
    severity: 'medium',
    priority_score: 19.5,
    upvotes: 5,
    ai_category: 'water',
    ai_confidence: 0.87,
    latitude: 40.7829,
    longitude: -73.9654,
    address: 'Central Park West, Manhattan, NY',
    reported_by: '4',
    assigned_to: '5',
    is_anonymous: false,
    created_at: '2024-03-08T12:00:00Z',
    updated_at: '2024-03-09T09:30:00Z',
    reporter: mockUsers[3],
    assignee: mockUsers[4],
  },
  {
    id: '5',
    ticket_id: 'IMP-2024-0005',
    title: 'Broken sidewalk',
    description: 'Cracked and uneven sidewalk creating a tripping hazard for pedestrians.',
    category: 'road',
    status: 'pending',
    severity: 'low',
    priority_score: 12.8,
    upvotes: 3,
    latitude: 40.7580,
    longitude: -73.9855,
    address: '567 Oak Street, Queens, NY',
    reported_by: '1',
    is_anonymous: false,
    created_at: '2024-03-12T15:20:00Z',
    updated_at: '2024-03-12T15:20:00Z',
    reporter: mockUsers[0],
  },
  {
    id: '6',
    ticket_id: 'IMP-2024-0006',
    title: 'Graffiti on public building',
    description: 'Offensive graffiti on the community center wall needs to be removed.',
    category: 'other',
    status: 'resolved',
    severity: 'low',
    priority_score: 11.2,
    upvotes: 2,
    photo_url: 'https://images.pexels.com/photos/1152851/pexels-photo-1152851.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7489,
    longitude: -73.9680,
    address: '234 West 42nd Street, New York, NY',
    is_anonymous: true,
    anonymous_contact: 'anon@temp.mail',
    created_at: '2024-02-25T10:00:00Z',
    updated_at: '2024-03-02T16:45:00Z',
  },
  {
    id: '7',
    ticket_id: 'IMP-2024-0007',
    title: 'Damaged traffic sign on Broadway',
    description: 'The stop sign at Broadway and 8th Street is badly damaged and barely visible. This is a serious safety hazard.',
    category: 'road',
    status: 'in_progress',
    severity: 'high',
    priority_score: 30.2,
    upvotes: 18,
    photo_url: 'https://images.pexels.com/photos/208087/pexels-photo-208087.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7614,
    longitude: -73.9776,
    address: '156 Broadway, Manhattan, NY',
    reported_by: '1',
    assigned_to: '4',
    is_anonymous: false,
    created_at: '2024-03-15T11:20:00Z',
    updated_at: '2024-03-15T11:20:00Z',
    reporter: mockUsers[0],
    assignee: mockUsers[3],
  },
  {
    id: '8',
    ticket_id: 'IMP-2024-0008',
    title: 'Broken public bench in Riverside Park',
    description: 'One of the benches near the playground has broken slats. Could be dangerous for children.',
    category: 'other',
    status: 'in_progress',
    severity: 'medium',
    priority_score: 16.5,
    upvotes: 6,
    photo_url: 'https://images.pexels.com/photos/2305165/pexels-photo-2305165.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7957,
    longitude: -73.9389,
    address: 'Riverside Park, Upper West Side, NY',
    reported_by: '1',
    assigned_to: '5',
    is_anonymous: false,
    created_at: '2024-03-18T14:35:00Z',
    updated_at: '2024-03-19T09:10:00Z',
    reporter: mockUsers[0],
    assignee: mockUsers[4],
  },
  {
    id: '9',
    ticket_id: 'IMP-2024-0009',
    title: 'Malfunctioning fire hydrant',
    description: 'Fire hydrant on Madison Avenue is continuously leaking water, creating a puddle on the sidewalk.',
    category: 'water',
    status: 'in_progress',
    severity: 'medium',
    priority_score: 21.4,
    upvotes: 9,
    latitude: 40.7614,
    longitude: -73.9733,
    address: '789 Madison Avenue, Manhattan, NY',
    reported_by: '4',
    assigned_to: '3',
    is_anonymous: false,
    created_at: '2024-03-20T08:45:00Z',
    updated_at: '2024-03-20T08:45:00Z',
    reporter: mockUsers[3],
    assignee: mockUsers[2],
  },
  {
    id: '10',
    ticket_id: 'IMP-2024-0010',
    title: 'Missing manhole cover',
    description: 'Dangerous open manhole on Washington Street. Immediate attention required to prevent accidents.',
    category: 'road',
    status: 'in_progress',
    severity: 'high',
    priority_score: 45.8,
    upvotes: 32,
    photo_url: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7143,
    longitude: -74.0090,
    address: '445 Washington Street, Downtown, NY',
    reported_by: '4',
    assigned_to: '3',
    is_anonymous: false,
    created_at: '2024-03-21T07:15:00Z',
    updated_at: '2024-03-21T08:00:00Z',
    reporter: mockUsers[3],
    assignee: mockUsers[2],
  },
  {
    id: '11',
    ticket_id: 'IMP-2024-0011',
    title: 'Flickering streetlights on 3rd Avenue',
    description: 'Multiple streetlights along 3rd Avenue are flickering constantly. Very annoying and potentially dangerous.',
    category: 'lighting',
    status: 'in_progress',
    severity: 'low',
    priority_score: 14.3,
    upvotes: 4,
    latitude: 40.7489,
    longitude: -73.9764,
    address: '3rd Avenue & 34th Street, Manhattan, NY',
    reported_by: '1',
    assigned_to: '5',
    is_anonymous: false,
    created_at: '2024-03-22T19:30:00Z',
    updated_at: '2024-03-22T19:30:00Z',
    reporter: mockUsers[0],
    assignee: mockUsers[4],
  },
  {
    id: '12',
    ticket_id: 'IMP-2024-0012',
    title: 'Illegal dumping near residential area',
    description: 'Large amount of construction debris dumped illegally near the apartment complex on Greene Street.',
    category: 'waste',
    status: 'resolved',
    severity: 'medium',
    priority_score: 24.6,
    upvotes: 11,
    photo_url: 'https://images.pexels.com/photos/3186574/pexels-photo-3186574.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7209,
    longitude: -74.0007,
    address: '127 Greene Street, SoHo, NY',
    reported_by: '1',
    is_anonymous: false,
    created_at: '2024-03-14T10:20:00Z',
    updated_at: '2024-03-17T16:30:00Z',
    reporter: mockUsers[0],
  },
  {
    id: '13',
    ticket_id: 'IMP-2024-0013',
    title: 'Cracked pavement on pedestrian crossing',
    description: 'Large cracks in the pavement at the pedestrian crossing on Lexington Avenue. Wheelchair users are having difficulty crossing safely.',
    category: 'road',
    status: 'in_progress',
    severity: 'high',
    priority_score: 33.7,
    upvotes: 27,
    photo_url: 'https://images.pexels.com/photos/257836/pexels-photo-257836.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7484,
    longitude: -73.9857,
    address: '876 Lexington Avenue, Manhattan, NY',
    reported_by: '4',
    assigned_to: '4',
    is_anonymous: false,
    created_at: '2024-03-23T08:15:00Z',
    updated_at: '2024-03-23T08:15:00Z',
    reporter: mockUsers[3],
    assignee: mockUsers[3],
  },
  {
    id: '14',
    ticket_id: 'IMP-2024-0014',
    title: 'Broken traffic light at busy intersection',
    description: 'Traffic light at the intersection of 5th Avenue and 42nd Street is not working properly. Red light stays on for too long causing traffic congestion.',
    category: 'other',
    status: 'in_progress',
    severity: 'high',
    priority_score: 41.2,
    upvotes: 38,
    photo_url: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7516,
    longitude: -73.9776,
    address: '5th Avenue & 42nd Street, Manhattan, NY',
    reported_by: '4',
    assigned_to: '3',
    is_anonymous: false,
    created_at: '2024-03-21T07:45:00Z',
    updated_at: '2024-03-22T10:30:00Z',
    reporter: mockUsers[3],
    assignee: mockUsers[2],
  },
  {
    id: '15',
    ticket_id: 'IMP-2024-0015',
    title: 'No lighting in subway station entrance',
    description: 'The lights at the entrance to the 7th Avenue subway station have been out for over two weeks. Very dark and unsafe at night.',
    category: 'lighting',
    status: 'in_progress',
    severity: 'high',
    priority_score: 36.4,
    upvotes: 44,
    latitude: 40.7590,
    longitude: -73.9845,
    address: '7th Avenue Subway Station, Manhattan, NY',
    reported_by: '4',
    assigned_to: '5',
    is_anonymous: false,
    created_at: '2024-03-19T21:30:00Z',
    updated_at: '2024-03-19T21:30:00Z',
    reporter: mockUsers[3],
    assignee: mockUsers[4],
  },
  {
    id: '16',
    ticket_id: 'IMP-2024-0016',
    title: 'Overflowing recycling bins at park',
    description: 'All recycling bins at Battery Park are completely full and overflowing. Recyclables are spilling onto the ground.',
    category: 'waste',
    status: 'in_progress',
    severity: 'medium',
    priority_score: 20.8,
    upvotes: 13,
    photo_url: 'https://images.pexels.com/photos/3178938/pexels-photo-3178938.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7033,
    longitude: -74.0170,
    address: 'Battery Park, Downtown, NY',
    reported_by: '3',
    assigned_to: '5',
    is_anonymous: false,
    created_at: '2024-03-24T11:00:00Z',
    updated_at: '2024-03-24T14:20:00Z',
    reporter: mockUsers[2],
    assignee: mockUsers[4],
  },
  {
    id: '17',
    ticket_id: 'IMP-2024-0017',
    title: 'Broken water fountain in public library',
    description: 'The water fountain on the second floor of the public library has been broken for months. Not dispensing any water.',
    category: 'water',
    status: 'in_progress',
    severity: 'low',
    priority_score: 9.3,
    upvotes: 7,
    latitude: 40.7532,
    longitude: -73.9822,
    address: '476 5th Avenue, New York Public Library, NY',
    reported_by: '4',
    assigned_to: '3',
    is_anonymous: false,
    created_at: '2024-03-20T15:45:00Z',
    updated_at: '2024-03-20T15:45:00Z',
    reporter: mockUsers[3],
    assignee: mockUsers[2],
  },
  {
    id: '18',
    ticket_id: 'IMP-2024-0018',
    title: 'Damaged playground equipment',
    description: 'The slide in the children\'s playground at Hudson River Park is damaged with sharp edges. Needs immediate repair for safety.',
    category: 'other',
    status: 'in_progress',
    severity: 'high',
    priority_score: 38.9,
    upvotes: 51,
    photo_url: 'https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7291,
    longitude: -74.0121,
    address: 'Hudson River Park, West Village, NY',
    reported_by: '4',
    assigned_to: '5',
    is_anonymous: false,
    created_at: '2024-03-22T10:00:00Z',
    updated_at: '2024-03-23T09:15:00Z',
    reporter: mockUsers[3],
    assignee: mockUsers[4],
  },
  {
    id: '19',
    ticket_id: 'IMP-2024-0019',
    title: 'Fallen tree blocking sidewalk',
    description: 'A large tree branch has fallen and is blocking the entire sidewalk on Amsterdam Avenue after the recent storm.',
    category: 'other',
    status: 'resolved',
    severity: 'high',
    priority_score: 42.1,
    upvotes: 29,
    photo_url: 'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=800',
    latitude: 40.7870,
    longitude: -73.9754,
    address: '2145 Amsterdam Avenue, Upper West Side, NY',
    reported_by: '3',
    is_anonymous: false,
    created_at: '2024-03-16T06:30:00Z',
    updated_at: '2024-03-16T15:45:00Z',
    reporter: mockUsers[2],
  },
  {
    id: '20',
    ticket_id: 'IMP-2024-0020',
    title: 'Faded pedestrian crossing markings',
    description: 'The white stripes of the pedestrian crossing on Houston Street are completely faded and barely visible. Dangerous for pedestrians.',
    category: 'road',
    status: 'in_progress',
    severity: 'medium',
    priority_score: 25.3,
    upvotes: 16,
    latitude: 40.7250,
    longitude: -73.9965,
    address: 'Houston Street & Lafayette, Manhattan, NY',
    reported_by: '3',
    assigned_to: '4',
    is_anonymous: false,
    created_at: '2024-03-25T09:20:00Z',
    updated_at: '2024-03-25T09:20:00Z',
    reporter: mockUsers[2],
    assignee: mockUsers[3],
  },
  {
    id: '21',
    ticket_id: 'IMP-2024-0021',
    title: 'Broken public restroom door lock',
    description: 'The lock on the public restroom at Union Square is broken. Door won\'t stay closed creating privacy and safety issues.',
    category: 'other',
    status: 'in_progress',
    severity: 'medium',
    priority_score: 18.7,
    upvotes: 12,
    latitude: 40.7359,
    longitude: -73.9911,
    address: 'Union Square Park, Manhattan, NY',
    reported_by: '4',
    assigned_to: '5',
    is_anonymous: false,
    created_at: '2024-03-24T16:10:00Z',
    updated_at: '2024-03-24T16:10:00Z',
    reporter: mockUsers[3],
    assignee: mockUsers[4],
  },
  {
    id: '22',
    ticket_id: 'IMP-2024-0022',
    title: 'Stagnant water pooling on street',
    description: 'Large puddle of stagnant water has been sitting on Canal Street for over a week after the rain. Mosquito breeding ground and bad smell.',
    category: 'water',
    status: 'in_progress',
    severity: 'medium',
    priority_score: 23.4,
    upvotes: 14,
    latitude: 40.7185,
    longitude: -74.0010,
    address: '345 Canal Street, Chinatown, NY',
    reported_by: '3',
    assigned_to: '5',
    is_anonymous: false,
    created_at: '2024-03-23T12:30:00Z',
    updated_at: '2024-03-24T08:00:00Z',
    reporter: mockUsers[2],
    assignee: mockUsers[4],
  },
];

export const mockIssueUpdates = {
  '1': [
    {
      id: 'u1',
      issue_id: '1',
      status: 'pending',
      comment: 'Issue reported and logged into our system.',
      updated_by: '2',
      created_at: '2024-03-01T09:35:00Z',
      updater: mockUsers[1],
    },
    {
      id: 'u2',
      issue_id: '1',
      status: 'in_progress',
      comment: 'Road repair team dispatched. Work will begin tomorrow.',
      updated_by: '3',
      created_at: '2024-03-05T14:20:00Z',
      updater: mockUsers[2],
    },
  ],
  '2': [
    {
      id: 'u3',
      issue_id: '2',
      status: 'in_progress',
      comment: 'Electrician team assigned to fix the streetlight.',
      updated_by: '2',
      created_at: '2024-02-22T10:00:00Z',
      updater: mockUsers[1],
    },
    {
      id: 'u4',
      issue_id: '2',
      status: 'resolved',
      comment: 'Streetlight has been repaired and is now functional.',
      updated_by: '2',
      created_at: '2024-02-28T10:15:00Z',
      updater: mockUsers[1],
    },
  ],
  '4': [
    {
      id: 'u5',
      issue_id: '4',
      status: 'in_progress',
      comment: 'Water department team is investigating the leak source.',
      updated_by: '5',
      created_at: '2024-03-09T09:30:00Z',
      updater: mockUsers[4],
    },
  ],
  '6': [
    {
      id: 'u6',
      issue_id: '6',
      status: 'in_progress',
      comment: 'Cleaning crew scheduled for tomorrow.',
      updated_by: '2',
      created_at: '2024-02-26T14:00:00Z',
      updater: mockUsers[1],
    },
    {
      id: 'u7',
      issue_id: '6',
      status: 'resolved',
      comment: 'Graffiti removed successfully.',
      updated_by: '2',
      created_at: '2024-03-02T16:45:00Z',
      updater: mockUsers[1],
    },
  ],
};

export const mockComments = {
  '1': [
    {
      id: 'c1',
      issue_id: '1',
      user_id: '4',
      comment: 'I also noticed this pothole yesterday. It\'s really dangerous, especially at night!',
      sentiment_score: -0.3,
      is_anonymous: false,
      created_at: '2024-03-02T10:15:00Z',
      commenter: mockUsers[3],
    },
    {
      id: 'c2',
      issue_id: '1',
      user_id: null,
      comment: 'My car tire was damaged because of this. Please fix it soon!',
      sentiment_score: -0.5,
      is_anonymous: true,
      created_at: '2024-03-03T14:30:00Z',
    },
    {
      id: 'c3',
      issue_id: '1',
      user_id: '1',
      comment: 'Thanks for the quick response! Looking forward to seeing it fixed.',
      sentiment_score: 0.6,
      is_anonymous: false,
      created_at: '2024-03-06T09:00:00Z',
      commenter: mockUsers[0],
    },
  ],
  '2': [
    {
      id: 'c4',
      issue_id: '2',
      user_id: '1',
      comment: 'Great job fixing this! The area feels much safer now.',
      sentiment_score: 0.8,
      is_anonymous: false,
      created_at: '2024-02-28T18:20:00Z',
      commenter: mockUsers[0],
    },
  ],
  '3': [
    {
      id: 'c5',
      issue_id: '3',
      user_id: '4',
      comment: 'This is becoming a health hazard. We need immediate action!',
      sentiment_score: -0.6,
      is_anonymous: false,
      created_at: '2024-03-11T09:30:00Z',
      commenter: mockUsers[3],
    },
    {
      id: 'c6',
      issue_id: '3',
      user_id: '3',
      comment: 'I have assigned a waste management team to address this issue. They will be on site within 24 hours.',
      sentiment_score: 0.4,
      is_anonymous: false,
      created_at: '2024-03-11T14:00:00Z',
      commenter: mockUsers[2],
    },
  ],
  '4': [
    {
      id: 'c7',
      issue_id: '4',
      user_id: '5',
      comment: 'I am investigating the water leak. Will provide an update on estimated repair time soon.',
      sentiment_score: 0.3,
      is_anonymous: false,
      created_at: '2024-03-09T10:00:00Z',
      commenter: mockUsers[4],
    },
    {
      id: 'c8',
      issue_id: '4',
      user_id: '4',
      comment: 'Thank you for looking into this. How long do you estimate the repair will take?',
      sentiment_score: 0.2,
      is_anonymous: false,
      created_at: '2024-03-09T15:30:00Z',
      commenter: mockUsers[3],
    },
  ],
  '7': [
    {
      id: 'c9',
      issue_id: '7',
      user_id: '1',
      comment: 'This sign is barely visible from 10 meters away. Very dangerous intersection!',
      sentiment_score: -0.4,
      is_anonymous: false,
      created_at: '2024-03-16T08:00:00Z',
      commenter: mockUsers[0],
    },
    {
      id: 'c10',
      issue_id: '7',
      user_id: '4',
      comment: 'Working on this now. New sign will be installed today. Should be complete by end of day.',
      sentiment_score: 0.5,
      is_anonymous: false,
      created_at: '2024-03-16T11:00:00Z',
      commenter: mockUsers[3],
    },
  ],
  '10': [
    {
      id: 'c11',
      issue_id: '10',
      user_id: '3',
      comment: 'This is an emergency situation. I have dispatched our urgent response team immediately. Area will be secured within the hour.',
      sentiment_score: 0.6,
      is_anonymous: false,
      created_at: '2024-03-21T07:30:00Z',
      commenter: mockUsers[2],
    },
    {
      id: 'c12',
      issue_id: '10',
      user_id: null,
      comment: 'Thank you for the quick response! I saw the team arrive and put up warning signs.',
      sentiment_score: 0.8,
      is_anonymous: true,
      created_at: '2024-03-21T08:45:00Z',
    },
  ],
  '13': [
    {
      id: 'c13',
      issue_id: '13',
      user_id: '1',
      comment: 'This affects wheelchair users and people with strollers. Really needs attention!',
      sentiment_score: -0.3,
      is_anonymous: false,
      created_at: '2024-03-23T10:00:00Z',
      commenter: mockUsers[0],
    },
  ],
  '15': [
    {
      id: 'c14',
      issue_id: '15',
      user_id: '5',
      comment: 'Electrical team is on the way. Estimated repair time is 2-3 hours.',
      sentiment_score: 0.4,
      is_anonymous: false,
      created_at: '2024-03-19T22:00:00Z',
      commenter: mockUsers[4],
    },
  ],
};

export const mockReactions = {
  '1': [
    { id: 'r1', issue_id: '1', user_id: '1', reaction_type: 'thumbsup', created_at: '2024-03-01T10:00:00Z' },
    { id: 'r2', issue_id: '1', user_id: '4', reaction_type: 'thumbsup', created_at: '2024-03-02T11:00:00Z' },
    { id: 'r3', issue_id: '1', user_id: '3', reaction_type: 'heart', created_at: '2024-03-03T14:00:00Z' },
  ],
  '2': [
    { id: 'r4', issue_id: '2', user_id: '1', reaction_type: 'celebrate', created_at: '2024-02-28T19:00:00Z' },
    { id: 'r5', issue_id: '2', user_id: '4', reaction_type: 'celebrate', created_at: '2024-02-28T20:00:00Z' },
  ],
  '3': [
    { id: 'r6', issue_id: '3', user_id: '4', reaction_type: 'thumbsup', created_at: '2024-03-11T10:00:00Z' },
  ],
};

export const mockNotifications = [
  {
    id: 'n1',
    user_id: '1',
    issue_id: '1',
    message: 'Your issue "Large pothole on Main Street" status changed to: in_progress',
    read: false,
    created_at: '2024-03-05T14:20:00Z',
  },
  {
    id: 'n2',
    user_id: '4',
    issue_id: '2',
    message: 'Your issue "Streetlight not working" status changed to: resolved',
    read: true,
    created_at: '2024-02-28T10:15:00Z',
  },
  {
    id: 'n3',
    user_id: '1',
    issue_id: '3',
    message: 'Your issue "Overflowing garbage bins" has received 10 new upvotes',
    read: false,
    created_at: '2024-03-11T15:30:00Z',
  },
  {
    id: 'n4',
    user_id: '1',
    issue_id: '7',
    message: 'Your issue "Damaged traffic sign on Broadway" has been assigned to Ward Officer Mike Johnson',
    read: false,
    created_at: '2024-03-25T10:15:00Z',
  },
  {
    id: 'n5',
    user_id: '1',
    issue_id: '8',
    message: 'Your issue "Broken public bench in Riverside Park" status changed to: in_progress',
    read: false,
    created_at: '2024-03-19T09:10:00Z',
  },
  {
    id: 'n6',
    user_id: '1',
    issue_id: '12',
    message: 'Your issue "Illegal dumping near residential area" status changed to: resolved',
    read: true,
    created_at: '2024-03-17T16:30:00Z',
  },
  {
    id: 'n7',
    user_id: '1',
    issue_id: '5',
    message: 'An admin commented on your issue "Broken sidewalk"',
    read: true,
    created_at: '2024-03-13T11:00:00Z',
  },
  {
    id: 'n8',
    user_id: '1',
    issue_id: '1',
    message: 'Your issue "Large pothole on Main Street" has received 5 new upvotes',
    read: false,
    created_at: '2024-03-24T14:30:00Z',
  },
  {
    id: 'n9',
    user_id: '1',
    issue_id: '11',
    message: 'Your issue "Flickering streetlights on 3rd Avenue" has been acknowledged by the city',
    read: false,
    created_at: '2024-03-23T08:00:00Z',
  },
  {
    id: 'n10',
    user_id: '1',
    message: 'Congratulations! You earned the "City Guardian" badge for reporting 20 verified issues',
    read: true,
    created_at: '2024-03-10T10:00:00Z',
  },
];

export const mockBadges = [
  {
    id: 'b1',
    name: 'First Reporter',
    description: 'Report your first issue',
    icon: '🌟',
    points_required: 10,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'b2',
    name: 'Community Helper',
    description: 'Report 5 verified issues',
    icon: '🤝',
    points_required: 50,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'b3',
    name: 'City Guardian',
    description: 'Report 20 verified issues',
    icon: '🛡️',
    points_required: 200,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'b4',
    name: 'Engagement Champion',
    description: 'Comment on 10 different issues',
    icon: '💬',
    points_required: 100,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'b5',
    name: 'Top Contributor',
    description: 'Reach 500 points',
    icon: '🏆',
    points_required: 500,
    created_at: '2024-01-01T00:00:00Z',
  },
];

export const mockUserBadges = {
  '1': [
    { id: 'ub1', user_id: '1', badge_id: 'b1', earned_at: '2024-03-01T09:30:00Z', badge: mockBadges[0] },
    { id: 'ub2', user_id: '1', badge_id: 'b2', earned_at: '2024-03-05T14:00:00Z', badge: mockBadges[1] },
    { id: 'ub3', user_id: '1', badge_id: 'b3', earned_at: '2024-03-10T10:00:00Z', badge: mockBadges[2] },
  ],
  '2': [
    { id: 'ub4', user_id: '2', badge_id: 'b1', earned_at: '2024-01-15T08:00:00Z', badge: mockBadges[0] },
    { id: 'ub5', user_id: '2', badge_id: 'b2', earned_at: '2024-01-20T10:00:00Z', badge: mockBadges[1] },
    { id: 'ub6', user_id: '2', badge_id: 'b3', earned_at: '2024-02-01T12:00:00Z', badge: mockBadges[2] },
    { id: 'ub7', user_id: '2', badge_id: 'b4', earned_at: '2024-02-10T14:00:00Z', badge: mockBadges[3] },
    { id: 'ub8', user_id: '2', badge_id: 'b5', earned_at: '2024-02-25T16:00:00Z', badge: mockBadges[4] },
  ],
  '4': [
    { id: 'ub9', user_id: '4', badge_id: 'b1', earned_at: '2024-02-20T18:45:00Z', badge: mockBadges[0] },
    { id: 'ub10', user_id: '4', badge_id: 'b2', earned_at: '2024-02-28T10:00:00Z', badge: mockBadges[1] },
    { id: 'ub11', user_id: '4', badge_id: 'b3', earned_at: '2024-03-08T12:00:00Z', badge: mockBadges[2] },
    { id: 'ub12', user_id: '4', badge_id: 'b5', earned_at: '2024-03-12T15:00:00Z', badge: mockBadges[4] },
  ],
};


// Current logged in user (for demo purposes)
export let currentMockUser = null;

export function setCurrentMockUser(user) {
  currentMockUser = user;
}

export function getMockUser() {
  return [...mockUsers];
}

export function createMockUser(email, fullName) {
  const newUser = {
    id: `user-${Date.now()}`,
    full_name: fullName,
    role: "citizen",
    email: email,
    notification_enabled: true,
    points: 0,
    language_preference: "en",
    created_at: new Date().toISOString(),
  };
  mockUsers.push(newUser);
  return newUser;
}

export function getIssues() {
  return [...mockIssues];
}

export function getIssueById(id) {
  return mockIssues.find((issue) => issue.id === id);
}

export function getCommentsByIssueId(issueId) {
  return mockComments.filter((comment) => comment.issue_id === issueId);
}

export function getReactionsByIssueId(issueId) {
  return mockReactions.filter((reaction) => reaction.issue_id === issueId);
}

export function getUpdatesByIssueId(issueId) {
  return mockUpdates.filter((update) => update.issue_id === issueId);
}

export function getNotificationsByUserId(userId) {
  return mockNotifications.filter((notif) => notif.user_id === userId);
}

export function getUnreadCount(userId) {
  return mockNotifications.filter(
    (notif) => notif.user_id === userId && !notif.read
  ).length;
}

let currentUser = null;

export function setCurrentUser(user) {
  currentUser = user;
  if (user) {
    localStorage.setItem("currentUser", JSON.stringify(user));
  } else {
    localStorage.removeItem("currentUser");
  }
}

export function getCurrentUser() {
  if (currentUser) return currentUser;
  const stored = localStorage.getItem("currentUser");
  if (stored) {
    currentUser = JSON.parse(stored);
  }
  return currentUser;
}
